services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: oraclepw
      APP_USER: app
      APP_USER_PASSWORD: apppw
    ports:
      - "1521:1521"
      - "5500:5500"
    shm_size: 1g
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s sys/oraclepw@localhost:1521/xepdb1 as sysdba || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  postgres:
    image: postgres:15
    container_name: postgre_test
    environment:
      POSTGRES_USER: postgre_test
      POSTGRES_PASSWORD: postgre_test
      POSTGRES_DB: postgre_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Ensure passwords are stored as scram and allow TCP host connections
    command:
      - -c
      - password_encryption=scram-sha-256
      - -c
      - listen_addresses=*
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre_test -d postgre_test -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 20

  mysql:
    image: mysql:8.4
    container_name: mysql84
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -p$${MYSQL_ROOT_PASSWORD} -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata: